# Generated by Django 4.1.2 on 2022-10-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_productmodel_sizel_productmodel_sizem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='isSizeL',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isSizeM',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isSizeS',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='isSizeXL',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
