# Generated by Django 4.1.2 on 2022-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_productmodel_issizel_productmodel_issizem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('GREEN', 'Green')], max_length=7, null=True),
        ),
    ]
