# Generated by Django 4.1.2 on 2022-10-29 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_productmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('WHITE', 'white'), ('BLACK', 'black'), ('GREY', 'grey'), ('BEIGE', 'beige'), ('GREEN', 'green')], max_length=7, null=True),
        ),
    ]
