# Generated by Django 4.1.2 on 2022-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_productmodel_date_alter_productmodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('GREY', 'Grey'), ('BEIGE', 'Beige'), ('GREEN', 'Green')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
