# Generated by Django 3.2.8 on 2022-10-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_productmodel_color_alter_productmodel_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImagesModel',
        ),
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShippingAddressModel',
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='size',
            field=models.CharField(choices=[('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl')], max_length=2, null=True),
        ),
    ]
