# Generated by Django 3.2.8 on 2022-11-05 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20221105_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagesmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productimages', to='mainApp.productmodel'),
        ),
    ]
