# Generated by Django 4.1.2 on 2023-02-25 14:58

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_productimagesmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='categoryFrontImgs'),
        ),
        migrations.AlterField(
            model_name='productimagesmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='productDetailsImgs'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Grey', 'Grey'), ('Beige', 'Beige'), ('Green', 'Green')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='frontImage',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='productFrontImgs'),
        ),
    ]
